onboarding = false

[theme]
name = "catppuccin"
auto_switch = false

[keys]
prefix = "ctrl+f"
goto = "prefix+s"
settings = "prefix+."
split_vertical = "prefix+|"

[ui]
sidebar_width = 20
sidebar_start_collapsed = true
sidebar_collapsed_mode = "hidden"

[ui.sidebar.spaces]
rows = [["state_icon", "workspace"]]
