# TPM (Tmux Plugin Manager) の設定
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# コピー機能の改善
set -g @plugin 'tmux-plugins/tmux-yank'

# セッションの保存・復元
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# ペイン操作の改善
set -g @plugin 'tmux-plugins/tmux-pain-control'

# Iceberg テーマ（iceberg-dark）
source-file '~/.config/tmux/iceberg_minimal.tmux.conf'

# TPM の初期化（ファイルの最後に記述）
run '~/.config/tmux/plugins/tpm/tpm'
